### PR TITLE
Disk i/o improvments, locks to prevent async collisions, e2e test improvements

### PR DESCRIPTION
**Pull request by tsortwehttam**
NOT READY TO MERGE.

This supersedes the #275 pull-request. (Bringing all changes into one commit, since there was a fair amount of back-and-forth that would make the original PR hard to read.)

Medium review.

Asana task links:

- https://app.asana.com/0/539750334128224/547237086617891
- https://app.asana.com/0/539750334128224/542311307465719
- https://app.asana.com/0/539750334128224/541984615586539

Changes in this PR:

- [x] @stristr Debounce writes to disk
- [x] @stristr Ensure fast updates to heavy stage elements doesn't destabilize editing
- [x] @matthewtoast Lock (mutex) certain in-mem updates to prevent race conditions
- [x] @matthewtoast Enforce sequential continuation in certain places
- [x] @matthewtoast Prevent stale file ingest from superseding in-mem updates
- [x] @matthewtoast Fix (reproducible) occurrences of `Cannot find element` crash
- [x] @matthewtoast Prevent `Cannot find module @haiku/core` crash
- [x] @matthewtoast Prevent a handful of bad property access-related crashes
- [x] @matthewtoast Improve e2e test harness

Notes for the reviewer:

- The most important changes are in File.js, ActiveComponent.js, and ModuleWrapper.js

- Skip everything having to do with e2e test or `executeFunctionSpecification`; we'll go over that as part of an automated testing workshop

- This will probably require thorough QA, at a minimum: the full E2E Checklist, all the ☣️-marked items in the QA Checklist, and a couple of people doing a couple of 30-minute slams

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [x] Did the [E2E checklist](https://haiku.quip.com/dGqeAEVSWdmg)
- [x] Ran the automated tests and linted the code
- [x] Wrote an automated test covering new functionality

### CODE REVIEW

**Comment by tsortwehttam** [comment]
Since the bulk of this has already been reviewed, and what is going on is fairly esoteric, I'm going to go ahead and merge to master so it can get put through its paces.
